[package]
name = "skyblock-rs"
version = "0.1.0"
authors = ["thinkier <26728734+thinkier@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper="0.13"
hyper-tls="0.4"
serde="*"
serde_json="*"
serde_derive="*"
base64="*"

[dependencies.futures]
version="0.3"
